project:
  type: website
  
website:
  title: "Classification non supervisée"
  navbar:
    background: lightseagreen
    left:
      - href: historique.qmd
        text: "Historique"
      - text: Modèles
        menu: 
          - href: modeles/mod_kmeans.qmd
            text: "Algorithme des K-means"
          - href: modeles/mod_CAH.qmd
            text: "Classification Ascendante hiérarchique (CAH)"
          - href: modeles/mod_mmelange.qmd
            text: "Modèles de mélange"
      - text: Exemples
        menu:
          - href: exemples/kmeans.qmd
            text: "Exemple de K-means avec R"
          - href: exemples/CAH.qmd
            text: "Exemple de CAH avec R"
          - href: exemples/CAH2.qmd
            text: "Exemple de CAH avec Python"
          - href: exemples/mmelange.qmd
            text: "Exemple de modèles de mélange"
          - href: exemples/kmeans_observable.qmd
            text: "Exemple de kmeans avec Observable"
      - text: Quizz
        href: quizz.qmd

    right:
      - text: About
        href: about.qmd
        
resources:
  - exemples/iris_clusters.json
format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
