project:
  type: website
  
website:
  title: "Classification non supervisée"
  navbar:
    background: lightseagreen
    left:
      - text: Présentation
        menu: 
          - href: presentation/definition.qmd
            text: "Définition"
          - href: presentation/historique.qmd
            text: "Historique"
      - text: Modèles
        menu: 
          - href: modeles/mod_kmeans.qmd
            text: "Algorithme des K-means"
          - href: modeles/mod_CAH.qmd
            text: "Classification Ascendante hiérarchique (CAH)"
          - href: modeles/mod_mmelange.qmd
            text: "Modèles de mélange"
      - text: Exemples
        menu:
          - href: exemples/kmeans.qmd
            text: "Exemples de K-means"
          - href: exemples/CAH.qmd
            text: "Exemples de CAH"
          - href: exemples/melange.qmd
            text: "Exemples de modèles de mélange"
          - href: exemples/kmeans_observable.qmd
            text: "Exemples de kmeans avec Observable"
    right:
      - about.qmd  
resources:
  - exemples/iris_clusters.json
format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
