## Articles fondateurs

- **MacQueen, J. (1967)**. *Some Methods for Classification and Analysis of Multivariate Observations*.  
  ➤ Article qui introduit l’algorithme des k-means.

- **Dempster, A. P., Laird, N. M., & Rubin, D. B. (1977)**. *Maximum Likelihood from Incomplete Data via the EM Algorithm*. *Journal of the Royal Statistical Society: Series B*, 39(1), 1–38.  
  ➤ Fondement de l’algorithme EM utilisé pour estimer les paramètres dans les modèles de mélange.

---

## Vidéos

- [Classification ascendante hiérarchique sur exemple simple](https://www.youtube.com/watch?v=Brfc-wGXDRg){target="_blank"}
- [Classification ascendante hiérarchique et application en python](https://www.youtube.com/watch?v=QabCGFzJDPM){target="_blank"}

## Exemples de code R ou Python

- [Clustering K-Means dans R ](https://statorials.org/k-signifie-regroupement-en-r/){target="_blank"}:butterfly:
- [Modèle de mélange gaussien](https://fr.wikipedia.org/wiki/Mod%C3%A8le_de_m%C3%A9lange_gaussien){target="_blank"}:dog:


### 🔹 Ressources en ligne

- [**Documentation officielle scikit-learn – Clustering**](https://scikit-learn.org/stable/modules/clustering.html)  
  ➤ Tutoriels Python : k-means, DBSCAN, GMM, etc.

- [**R-bloggers – Articles sur le clustering**](https://www.r-bloggers.com/tag/clustering/)  
  ➤ Tutoriels en R sur les méthodes de classification non supervisée.

- [**Cours ENSAI / ENSAE – Classification non supervisée**](https://ensae.fr/)  
  ➤ Supports de cours en statistique pour étudiants et chercheurs.
