
---
title: "Algorithme CAH en utilisant Python"
author: "Olivier Malahel"
format: html
from: markdown+emoji
code-block-bg: true
code-block-border-left: "#31BAE9"
---


## Exemple

Enjeu : On souhaite regrouper les pays selon leur PIB, leur espérance de vie et leur taux d'alphabétisation. 

### Import des bibliothèques

```{python}
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
df = pd.read_csv("donnees_pays.csv")
```


### Chargement les données 
```{python}
df = pd.read_csv("donnees_pays.csv")
df.head()
```

### Normalisation avec sklearn
```{python}
X = df[["PIB_par_hab", "Espérance_de_vie", "Taux_alphabétisation"]]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
```

### Calcul des liens hiérarchiques (Ward)
```{python}
Z = linkage(X_scaled, method="ward")
```

### Affichage du dendrogramme avec ligne de coupure
```{python}
plt.figure(figsize=(10, 5))
dendrogram(Z, labels=df["Pays"].values, leaf_rotation=90)
plt.axhline(
    y=Z[-3, 2] + 0.5,
    c='red',
    linestyle='--',
    label="Coupure à 3 clusters"
)
plt.title("Dendrogramme - Classification Hiérarchique")
plt.ylabel("Distance")
plt.legend()
plt.tight_layout()
plt.show()
```

### Découpage en 3 clusters
```{python}
df["Cluster"] = fcluster(Z, t=3, criterion="maxclust")
df[["Pays", "Cluster"]]
```

## Conclusion : 

La CAH permet d'identifier 3 groupes de Pays: 

- Cluster 1 : Nigeria, Afrique du Sud, Inde, Égypte. 

Ce sont les pays avec un développement faible (PIB par habitant plus faible, espérance de vie plus courte, taux d’alphabétisation relativement bas)

- Cluster 2: Russie, Indonésie, Brésil, Argentine, Turquie, Chine, Mexique

Ce sont des pays émergents avec un niveau de développement économique moyen, une amélioration progressive de l’espérance de vie et de l’éducation,

et un fort potentiel économique. 

- Cluster 3 : États-Unis, Canada, Australie, Japon, Italie, Espagne, Corée du Sud, France, Allemagne

Ce sont les pays développés ayant un PIB par habitant élevé, une espérance de vie longue, et un taux d’alphabétisation proche de 100%.